package reflection;

public class Junit3Test {
    public String test1() throws Exception {
        System.out.println("Running Test1");
        return "test1()의 결과값!";
    }

    public String test2() throws Exception {
        System.out.println("Running Test2");
        return "test2()의 결과값!";
    }

    public void three() throws Exception {
        System.out.println("Running Test3");
    }
}
